# Generated by Django 4.2.20 on 2025-04-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_classifiedad_description_classifiedad_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifiedad',
            options={'ordering': ['-created_at']},
        ),
    ]
