# Generated by Django 4.2.20 on 2025-04-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_classifiedad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifiedad',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='classifiedad',
            old_name='created_at',
            new_name='scraped_at',
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
